In [ ]:
from pycoingecko import CoinGeckoAPI
cg = CoinGeckoAPI()
bitcoin_data = cg.get_coin_market_chart_by_id(id='bitcoin', vs_currency='usd', days=30)
bitcoin_data

{'prices': [[1786118400000, 64890.3693115144],
  [1786122000000, 64784.443235545856],
  [1786125600000, 64717.55365296767],
  [1786129200000, 64681.58780407244],
  [1786132800000, 64924.48832316786],
  [1786136400000, 64932.89561541767],
  [1786140000000, 64893.94834551407],
  [1786143600000, 64850.448382153656],
  [1786147200000, 64879.7560855934],
  [1786150800000, 64883.781921085414],
  [1786154400000, 64878.44290990822],
  [1786158000000, 64888.60024243567],
  [1786161600000, 64991.800307001715],
  [1786165200000, 64974.34511475399],
  [1786168800000, 64957.319898406],
  [1786172400000, 64971.202151693644],
  [1786176000000, 64926.53145827044],
  [1786179600000, 64955.56049646456],
  [1786183200000, 64953.96139341334],
  [1786186800000, 64966.51707986603],
  [1786190400000, 64929.03814455765],
  [1786194000000, 64967.17250978196],
  [1786197600000, 64973.31853419001],
  [1786201200000, 65091.586338816014],
  [1786204800000, 65036.76339051263],
  [1786208400000, 65039.855667855074],
  [1786212000000, 65070.90755918463],
  [1786215600000, 64996.35672497409],
  [1786219200000, 65029.86941572282],
  [1786222800000, 65033.19724140798],
  [1786226400000, 64970.595472780034],
  [1786230000000, 64906.29560481423],
  [1786233600000, 64917.23929330571],
  [1786237200000, 64930.16988675851],
  [1786240800000, 64821.736551433125],
  [1786244400000, 64777.43245005261],
  [1786248000000, 64746.24640603082],
  [1786251600000, 64742.165175431466],
  [1786255200000, 64757.534520212444],
  [1786258800000, 64808.68595819708],
  [1786262400000, 64784.28632322148],
  [1786266000000, 64776.107760186096],
  [1786269600000, 64827.034541497196],
  [1786273200000, 64912.19259865948],
  [1786276800000, 64906.2713042924],
  [1786280400000, 64908.10005558104],
  [1786284000000, 65171.70960979203],
  [1786287600000, 65211.91638656913],
  [1786291200000, 65187.34268543269],
  [1786294800000, 65187.438808289626],
  [1786298400000, 65156.107326992525],
  [1786302000000, 65157.33057894149],
  [1786305600000, 65140.38760870087],
  [1786309200000, 65097.39156558012],
  [1786312800000, 65160.37598329928],
  [1786316400000, 65029.73017130765],
  [1786320000000, 64856.097825382276],
  [1786323600000, 64921.25010696196],
  [1786327200000, 65146.98539896946],
  [1786330800000, 65050.92775618636],
  [1786334400000, 64926.61865449755],
  [1786338000000, 64963.519059919934],
  [1786341600000, 65094.117820878906],
  [1786345200000, 65248.67295158608],
  [1786348800000, 65167.213663218245],
  [1786352400000, 65195.68633970625],
  [1786356000000, 64917.33581821922],
  [1786359600000, 64962.770897856935],
  [1786363200000, 65067.14612088838],
  [1786366800000, 64823.06855440583],
  [1786370400000, 64504.87043578211],
  [1786374000000, 64580.08513698282],
  [1786377600000, 64227.27646268125],
  [1786381200000, 63840.93020728684],
  [1786384800000, 63892.11420985093],
  [1786388400000, 63838.22058073376],
  [1786392000000, 63973.13623771109],
  [1786395600000, 64103.631399788326],
  [1786399200000, 63933.972785363185],
  [1786402800000, 63959.64355474596],
  [1786406400000, 63915.71213556821],
  [1786410000000, 63981.67534094522],
  [1786413600000, 64013.0197751689],
  [1786417200000, 63987.500225201475],
  [1786420800000, 64084.512233362526],
  [1786424400000, 63969.548506599895],
  [1786428000000, 63943.63242630121],
  [1786431600000, 63899.78853749887],
  [1786435200000, 64005.60344741368],
  [1786438800000, 64078.127040366926],
  [1786442400000, 64228.37489652754],
  [1786446000000, 64187.59814192965],
  [1786449600000, 64338.89343571287],
  [1786453200000, 64299.68705896488],
  [1786456800000, 64182.22631568661],
  [1786460400000, 63717.8101572953],
  [1786464000000, 63561.0383467955],
  [1786467600000, 63459.53175568126],
  [1786471200000, 63545.21783083028],
  [1786474800000, 63312.694402340094],
  [1786478400000, 63474.26282448312],
  [1786482000000, 63681.01588484284],
  [1786485600000, 63623.55117550987],
  [1786489200000, 63614.06881811433],
  [1786492800000, 63537.55988964766],
  [1786496400000, 63689.061367716],
  [1786500000000, 63761.047124254495],
  [1786503600000, 63679.47238781192],
  [1786507200000, 63773.80880878046],
  [1786510800000, 63718.3939824206],
  [1786514400000, 63782.06682273836],
  [1786518000000, 63642.89363336196],
  [1786521600000, 63763.800734015305],
  [1786525200000, 63733.95353057831],
  [1786528800000, 64048.61366886717],
  [1786532400000, 64092.90806681466],
  [1786536000000, 64181.4177302335],
  [1786539600000, 64070.60628088705],
  [1786543200000, 63784.21064350375],
  [1786546800000, 63317.67085189585],
  [1786550400000, 63384.7882093211],
  [1786554000000, 63434.34135659124],
  [1786557600000, 63410.30532735148],
  [1786561200000, 63330.69946315327],
  [1786564800000, 63355.10675260609],
  [1786568400000, 63525.24734422619],
  [1786572000000, 63415.52706407907],
  [1786575600000, 63369.41905225762],
  [1786579200000, 63408.625697113624],
  [1786582800000, 63504.7637721623],
  [1786586400000, 63402.068403911784],
  [1786590000000, 63486.86595222896],
  [1786593600000, 63585.54151306996],
  [1786597200000, 63636.58188426853],
  [1786600800000, 63817.464427205356],
  [1786604400000, 63872.55836974137],
  [1786608000000, 63808.407329993664],
  [1786611600000, 63709.087979671305],
  [1786615200000, 63741.669102566724],
  [1786618800000, 63591.226200807796],
  [1786622400000, 63408.23142353863],
  [1786626000000, 63634.86677886916],
  [1786629600000, 63652.08273290709],
  [1786633200000, 63815.453359095525],
  [1786636800000, 63401.298765362255],
  [1786640400000, 63061.808897657276],
  [1786644000000, 63089.6589821604],
  [1786647600000, 63253.26387148011],
  [1786651200000, 63348.80377496922],
  [1786654800000, 63344.29952858219],
  [1786658400000, 63417.214907609006],
  [1786662000000, 63475.08612169292],
  [1786665600000, 63429.17906286841],
  [1786669200000, 63481.25601936451],
  [1786672800000, 63513.29452934755],
  [1786676400000, 63422.04788788586],
  [1786680000000, 63277.505851880036],
  [1786683600000, 63311.36450145151],
  [1786687200000, 63351.88300325618],
  [1786690800000, 62915.42176685937],
  [1786694400000, 62871.97528092776],
  [1786698000000, 62874.788984946375],
  [1786701600000, 62718.49376116481],
  [1786705200000, 62752.77530783759],
  [1786708800000, 62822.24207508047],
  [1786712400000, 62675.53203107954],
  [1786716000000, 62575.57300838414],
  [1786719600000, 62575.05117640368],
  [1786723200000, 62938.94185062359],
  [1786726800000, 63074.16141661424],
  [1786730400000, 62947.83733432764],
  [1786734000000, 62863.41493276841],
  [1786737600000, 62899.16125413761],
  [1786741200000, 62848.73561827566],
  [1786744800000, 62864.91750277205],
  [1786748400000, 62829.82451631032],
  [1786752000000, 62984.28959582886],
  [1786755600000, 62959.020399589834],
  [1786759200000, 62984.560804532324],
  [1786762800000, 63075.20954725237],
  [1786766400000, 62993.64686315622],
  [1786770000000, 63064.461933311264],
  [1786773600000, 63029.88219350657],
  [1786777200000, 63056.18471238017],
  [1786780800000, 63020.41823015727],
  [1786784400000, 62879.52138602643],
  [1786788000000, 62968.70612462649],
  [1786791600000, 62980.93432376597],
  [1786795200000, 62959.89459290653],
  [1786798800000, 62986.960981818425],
  [1786802400000, 62996.31237232209],
  [1786806000000, 62981.664765813024],
  [1786809600000, 63041.13901639061],
  [1786813200000, 63037.00396331667],
  [1786816800000, 63008.94500446156],
  [1786820400000, 62993.70114557048],
  [1786824000000, 63063.40824351767],
  [1786827600000, 63043.359786471054],
  [1786831200000, 63099.90357904285],
  [1786834800000, 63076.88847073649],
  [1786838400000, 63031.04825975698],
  [1786842000000, 63026.59822523408],
  [1786845600000, 63024.52145938261],
  [1786849200000, 63068.423175346055],
  [1786852800000, 63074.58460926518],
  [1786856400000, 63041.31239712379],
  [1786860000000, 63012.24310239301],
  [1786863600000, 63015.2386910052],
  [1786867200000, 63007.2882354478],
  [1786870800000, 63016.681736113525],
  [1786874400000, 62938.045504395865],
  [1786878000000, 62954.007865844076],
  [1786881600000, 62955.61808621155],
  [1786885200000, 62964.78297594083],
  [1786888800000, 63005.698278632524],
  [1786892400000, 63045.45440142677],
  [1786896000000, 63086.1217944101],
  [1786899600000, 63201.049074677474],
  [1786903200000, 63100.98084291131],
  [1786906800000, 63087.15019059952],
  [1786910400000, 63056.452393376916],
  [1786914000000, 63013.630293589886],
  [1786917600000, 62894.59271109232],
  [1786921200000, 62837.382987077195],
  [1786924800000, 62843.70368466329],
  [1786928400000, 62856.40917575992],
  [1786932000000, 63069.34140921656],
  [1786935600000, 63350.1906229179],
  [1786939200000, 63396.47170987772],
  [1786942800000, 63489.131405128144],
  [1786946400000, 63467.90027489531],
  [1786950000000, 63607.93511526065],
  [1786953600000, 63481.535981923385],
  [1786957200000, 63326.431998602755],
  [1786960800000, 63261.753456538805],
  [1786964400000, 63612.58725649707],
  [1786968000000, 63566.842736501225],
  [1786971600000, 63496.76290564356],
  [1786975200000, 63598.70569612954],
  [1786978800000, 63818.55305981763],
  [1786982400000, 64142.28936613087],
  [1786986000000, 64057.6832839486],
  [1786989600000, 64278.142511779304],
  [1786993200000, 64371.149002416234],
  [1786996800000, 64241.03743533318],
  [1787000400000, 64341.446093494706],
  [1787004000000, 64333.108425393846],
  [1787007600000, 64239.05708328847],
  [1787011200000, 64491.345282946255],
  [1787014800000, 64321.133481444536],
  [1787018400000, 64142.37370958817],
  [1787022000000, 64043.438153160605],
  [1787025600000, 64121.610806267905],
  [1787029200000, 64152.4092356144],
  [1787032800000, 64181.797885533524],
  [1787036400000, 64259.768446518225],
  [1787040000000, 64141.5681057857],
  [1787043600000, 64217.99410529414],
  [1787047200000, 64113.131516149195],
  [1787050800000, 64143.146452954694],
  [1787054400000, 64283.73806375364],
  [1787058000000, 64157.62131397192],
  [1787061600000, 64165.81470769047],
  [1787065200000, 64693.18187463143],
  [1787068800000, 64817.622769279034],
  [1787072400000, 64790.82377426676],
  [1787076000000, 64633.935075403606],
  [1787079600000, 64735.12660587504],
  [1787083200000, 64608.08190950003],
  [1787086800000, 64547.98463837647],
  [1787090400000, 64560.88328806326],
  [1787094000000, 64595.783635717016],
  [1787097600000, 64686.25782561655],
  [1787101200000, 64452.31711578264],
  [1787104800000, 64358.657923674895],
  [1787108400000, 64307.0555094849],
  [1787112000000, 64282.74748343018],
  [1787115600000, 64269.98266265912],
  [1787119200000, 64196.773428830034],
  [1787122800000, 64292.979289674884],
  [1787126400000, 64249.82027485047],
  [1787130000000, 64368.06288435155],
  [1787133600000, 64373.182382151004],
  [1787137200000, 64400.501085684926],
  [1787140800000, 64463.48880683975],
  [1787144400000, 64817.74091095421],
  [1787148000000, 64988.84033830409],
  [1787151600000, 65888.13114700055],
  [1787155200000, 68529.2604448789],
  [1787158800000, 68446.0506654718],
  [1787162400000, 68177.48759530894],
  [1787166000000, 68363.69093179365],
  [1787169600000, 68413.7738008957],
  [1787173200000, 69051.13834939648],
  [1787176800000, 69709.88783908814],
  [1787180400000, 69221.13960793983],
  [1787184000000, 69291.0104297816],
  [1787187600000, 69371.09419653316],
  [1787191200000, 69678.75316831222],
  [1787194800000, 69254.31368667162],
  [1787198400000, 69147.02249937781],
  [1787202000000, 69447.45529598776],
  [1787205600000, 69357.96397327346],
  [1787209200000, 69805.54705248833],
  [1787212800000, 69760.08785312675],
  [1787216400000, 71557.12878114937],
  [1787220000000, 71725.38179193603],
  [1787223600000, 71925.06682629428],
  [1787227200000, 71877.57267444955],
  [1787230800000, 71889.217266767],
  [1787234400000, 71618.68288965462],
  [1787238000000, 71748.96417152091],
  [1787241600000, 72425.67227407642],
  [1787245200000, 72784.72068116134],
  [1787248800000, 72758.30528271197],
  [1787252400000, 72408.47169123203],
  [1787256000000, 72643.17015936306],
  [1787259600000, 72642.87853789292],
  [1787263200000, 72720.75785176031],
  [1787266800000, 72660.83666004494],
  [1787270400000, 73020.94563440893],
  [1787274000000, 73668.68338381291],
  [1787277600000, 75093.24557294855],
  [1787281200000, 74403.43561267677],
  [1787284800000, 74501.33277079568],
  [1787288400000, 74976.42430989878],
  [1787292000000, 75401.27314952141],
  [1787295600000, 75589.61110387047],
  [1787299200000, 76264.24750920974],
  [1787302800000, 79217.9483974556],
  [1787306400000, 77864.10497946087],
  [1787310000000, 77794.118340972],
  [1787313600000, 76713.5634569039],
  [1787317200000, 77182.33751655415],
  [1787320800000, 77240.58586265544],
  [1787324400000, 77342.40360768468],
  [1787328000000, 77191.7297405987],
  [1787331600000, 77463.76264787953],
  [1787335200000, 77375.10851594472],
  [1787338800000, 77076.68038587937],
  [1787342400000, 77019.47423910756],
  [1787346000000, 77469.94144228443],
  [1787349600000, 78492.97073193404],
  [1787353200000, 78447.00174629269],
  [1787356800000, 78317.77716345884],
  [1787360400000, 77924.47841173135],
  [1787364000000, 77861.62585151519],
  [1787367600000, 78450.87361456598],
  [1787371200000, 78416.76241519109],
  [1787374800000, 78459.51007247694],
  [1787378400000, 77357.59793471967],
  [1787382000000, 77467.10685228396],
  [1787385600000, 77278.78002614668],
  [1787389200000, 77181.36893842522],
  [1787392800000, 77033.02620193096],
  [1787396400000, 76956.59153941978],
  [1787400000000, 77108.11920139303],
  [1787403600000, 77293.99101326858],
  [1787407200000, 77276.14980501754],
  [1787410800000, 76987.90262084498],
  [1787414400000, 76964.49140518492],
  [1787418000000, 77292.8831428596],
  [1787421600000, 77266.89526794103],
  [1787425200000, 77231.22250751803],
  [1787428800000, 77413.69625242811],
  [1787432400000, 77304.87657970993],
  [1787436000000, 76854.12177327243],
  [1787439600000, 76998.18180233128],
  [1787443200000, 77081.02299000922],
  [1787446800000, 77290.19616788143],
  [1787450400000, 77177.16566896404],
  [1787454000000, 77064.85571990619],
  [1787457600000, 76922.75881020405],
  [1787461200000, 76603.68260333966],
  [1787464800000, 76083.9882392138],
  [1787468400000, 76081.55334508924],
  [1787472000000, 75971.01505121416],
  [1787475600000, 76465.84871139617],
  [1787479200000, 76544.84171512509],
  [1787482800000, 76776.90646869465],
  [1787486400000, 77292.24300322762],
  [1787490000000, 77197.80300407711],
  [1787493600000, 77466.11997569115],
  [1787497200000, 77164.3936869177],
  [1787500800000, 77160.89722861466],
  [1787504400000, 77413.88248105405],
  [1787508000000, 77191.31549393748],
  [1787511600000, 77326.15251540612],
  [1787515200000, 77329.71083204656],
  [1787518800000, 77394.20563765302],
  [1787522400000, 77825.21064991705],
  [1787526000000, 77588.632845203],
  [1787529600000, 77712.3200924702],
  [1787533200000, 77653.79804479145],
  [1787536800000, 76945.96840911577],
  [1787540400000, 77457.84242039738],
  [1787544000000, 76947.53018623627],
  [1787547600000, 76869.96454486565],
  [1787551200000, 77147.65700118034],
  [1787554800000, 77456.55690404038],
  [1787558400000, 77294.09640124028],
  [1787562000000, 77013.63410094751],
  [1787565600000, 77527.46226157369],
  [1787569200000, 77595.54488263429],
  [1787572800000, 78344.16814933078],
  [1787576400000, 79133.98779733223],
  [1787580000000, 78563.89035232773],
  [1787583600000, 79458.02372190669],
  [1787587200000, 79027.40904999354],
  [1787590800000, 79041.8506333722],
  [1787594400000, 78747.19585805369],
  [1787598000000, 78924.08457973282],
  [1787601600000, 78745.95444275552],
  [1787605200000, 78912.78244129632],
  [1787608800000, 78965.23807968173],
  [1787612400000, 78727.75628402238],
  [1787616000000, 78973.88693602335],
  [1787619600000, 79726.56639658313],
  [1787623200000, 79798.96543790487],
  [1787626800000, 80638.19676744967],
  [1787630400000, 80454.83096255799],
  [1787634000000, 80332.74384336048],
  [1787637600000, 80697.54254113196],
  [1787641200000, 80526.82298900929],
  [1787644800000, 79722.30111409762],
  [1787648400000, 79907.40421315166],
  [1787652000000, 79156.6318959654],
  [1787655600000, 79297.49284303172],
  [1787659200000, 79117.66650635944],
  [1787662800000, 78972.97408414057],
  [1787666400000, 78600.91532693956],
  [1787670000000, 79223.1721233044],
  [1787673600000, 79498.8934370439],
  [1787677200000, 79140.47886151345],
  [1787680800000, 79230.95939211696],
  [1787684400000, 79124.339918888],
  [1787688000000, 78924.6713913788],
  [1787691600000, 78199.0582107816],
  [1787695200000, 78566.13452229745],
  [1787698800000, 78879.4177779762],
  [1787702400000, 78511.2331116067],
  [1787706000000, 78625.61544180397],
  [1787709600000, 78811.09430064046],
  [1787713200000, 79096.82822982507],
  [1787716800000, 79069.0901403206],
  [1787720400000, 78815.58561628273],
  [1787724000000, 79060.71623282021],
  [1787727600000, 78930.1698975655],
  [1787731200000, 78913.1467133613],
  [1787734800000, 78675.50711949496],
  [1787738400000, 78423.32059652456],
  [1787742000000, 78712.43221920858],
  [1787745600000, 78472.10325182501],
  [1787749200000, 78325.11196243031],
  [1787752800000, 78436.34785342895],
  [1787756400000, 77778.81759411356],
  [1787760000000, 78011.0248049709],
  [1787763600000, 77992.9645061395],
  [1787767200000, 78425.3872558423],
  [1787770800000, 78462.78992712124],
  [1787774400000, 78454.8306474836],
  [1787778000000, 78443.5651838574],
  [1787781600000, 78706.17814257603],
  [1787785200000, 78708.99798302965],
  [1787788800000, 79018.03405750773],
  [1787792400000, 78702.39106385609],
  [1787796000000, 78906.21090289645],
  [1787799600000, 78717.16727941387],
  [1787803200000, 78817.00293207057],
  [1787806800000, 78761.6101358522],
  [1787810400000, 78872.10921659994],
  [1787814000000, 78800.49362607743],
  [1787817600000, 79074.23394794346],
  [1787821200000, 79691.28956416981],
  [1787824800000, 79981.02030000853],
  [1787828400000, 79596.88892982739],
  [1787832000000, 79479.42013840542],
  [1787835600000, 79292.77437944377],
  [1787839200000, 79512.64023477088],
  [1787842800000, 80190.32101475948],
  [1787846400000, 80329.18870706021],
  [1787850000000, 80381.45508232129],
  [1787853600000, 80453.84935448112],
  [1787857200000, 80122.89392879306],
  [1787860800000, 79938.27018342797],
  [1787864400000, 80083.09621459675],
  [1787868000000, 80181.41607946662],
  [1787871600000, 80297.0041788454],
  [1787875200000, 80268.37474707834],
  [1787878800000, 80591.31114455192],
  [1787882400000, 80500.65742009522],
  [1787886000000, 79935.57059402476],
  [1787889600000, 79818.12475925282],
  [1787893200000, 79647.27780794752],
  [1787896800000, 79696.44412894675],
  [1787900400000, 79911.61337955634],
  [1787904000000, 79687.2427995466],
  [1787907600000, 79513.04910479934],
  [1787911200000, 79292.20300894548],
  [1787914800000, 79557.5601810478],
  [1787918400000, 79600.2788053087],
  [1787922000000, 79407.60449431959],
  [1787925600000, 79438.06518585574],
  [1787929200000, 79607.76745531596],
  [1787932800000, 78370.57900691858],
  [1787936400000, 77798.28323867955],
  [1787940000000, 77896.96429182867],
  [1787943600000, 77532.27507668122],
  [1787947200000, 77528.00468786708],
  [1787950800000, 77398.34418104916],
  [1787954400000, 77346.05408680951],
  [1787958000000, 77738.78291524075],
  [1787961600000, 77820.76428719184],
  [1787965200000, 77727.30394647292],
  [1787968800000, 77790.60032689421],
  [1787972400000, 77669.86720102842],
  [1787976000000, 77512.81226451545],
  [1787979600000, 77645.86029492349],
  [1787983200000, 77629.1915003392],
  [1787986800000, 77461.03011140913],
  [1787990400000, 77634.23863196258],
  [1787994000000, 77634.0205335061],
  [1787997600000, 77649.82587406744],
  [1788001200000, 77644.01867275102],
  [1788004800000, 77583.93504642752],

In [ ]:
import pandas as pd 
data= pd.DataFrame(bitcoin_data['prices'], columns=['timestamp', 'price'])
data

         timestamp         price
0    1786118400000  64890.369312
1    1786122000000  64784.443236
2    1786125600000  64717.553653
3    1786129200000  64681.587804
4    1786132800000  64924.488323
..             ...           ...
716  1788696000000  79911.779817
717  1788699600000  79918.626829
718  1788703200000  79806.906652
719  1788706800000  79526.796740
720  1788708770000  79610.313516

[721 rows x 2 columns]

In [ ]:
data['DATE'] = pd.to_datetime(data['timestamp'], unit='ms')
data

         timestamp         price                DATE
0    1786118400000  64890.369312 2026-08-07 16:00:00
1    1786122000000  64784.443236 2026-08-07 17:00:00
2    1786125600000  64717.553653 2026-08-07 18:00:00
3    1786129200000  64681.587804 2026-08-07 19:00:00
4    1786132800000  64924.488323 2026-08-07 20:00:00
..             ...           ...                 ...
716  1788696000000  79911.779817 2026-09-06 12:00:00
717  1788699600000  79918.626829 2026-09-06 13:00:00
718  1788703200000  79806.906652 2026-09-06 14:00:00
719  1788706800000  79526.796740 2026-09-06 15:00:00
720  1788708770000  79610.313516 2026-09-06 15:32:50

[721 rows x 3 columns]

In [ ]:
candlestick_data = data.groupby(data['DATE'].dt.date).agg({'price': ['first', 'max', 'min', 'last']})

In [ ]:
import plotly.graph_objects as go
fig = go.Figure(data=[go.Candlestick(x=candlestick_data.index,
                                     open=candlestick_data[('price', 'first')],
                                     high=candlestick_data[('price', 'max')],
                                     low=candlestick_data[('price', 'min')],
                                     close=candlestick_data[('price', 'last')])])
fig.update_layout(title='Bitcoin Candlestick Chart', xaxis_title='Date', yaxis_title='Price (USD)')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'close': {'bdata': ('woclWU6q70A1Oph1SbHvQNs3kF23wO' ... 'wADnLzQLtgePFQevNAhpUpBKVv80A='),
                        'dtype': 'f8'},
              'high': {'bdata': ('FqrhqJy070DlnknDcsjvQB3tCVN91+' ... 'c5C9fzQCGgEM1Zi/NAngpgHaWJ80A='),
                       'dtype': 'f8'},
              'low': {'bdata': ('c3xKzzKV70BcZlEszq3vQIj8HUnFnO' ... 'xUbETzQItu55mUafNAVUxyv2xq80A='),
                      'dtype': 'f8'},
              'open': {'bdata': ('jGFm0Uuv70AUatox+K3vQEZvSqinsu' ... 'c5C9fzQMz7bh90c/NArGQBLtt880A='),
                       'dtype': 'f8'},
              'type': 'candlestick',
              'x': array([datetime.date(2026, 8, 7), datetime.date(2026, 8, 8),
                          datetime.date(2026, 8, 9), datetime.date(2026, 8, 10),
                          datetime.date(2026, 8, 11), datetime.date(2026, 8, 12),
                          datetime.date(2026, 8, 13), datetime.date(2026, 8, 14),
                          datetime.date(2026, 8, 15), datetime.date(2026, 8, 16),
                          datetime.date(2026, 8, 17), datetime.date(2026, 8, 18),
                          datetime.date(2026, 8, 19), datetime.date(2026, 8, 20),
                          datetime.date(2026, 8, 21), datetime.date(2026, 8, 22),
                          datetime.date(2026, 8, 23), datetime.date(2026, 8, 24),
                          datetime.date(2026, 8, 25), datetime.date(2026, 8, 26),
                          datetime.date(2026, 8, 27), datetime.date(2026, 8, 28),
                          datetime.date(2026, 8, 29), datetime.date(2026, 8, 30),
                          datetime.date(2026, 8, 31), datetime.date(2026, 9, 1),
                          datetime.date(2026, 9, 2), datetime.date(2026, 9, 3),
                          datetime.date(2026, 9, 4), datetime.date(2026, 9, 5),
                          datetime.date(2026, 9, 6)], dtype=object)}],
    'layout': {'template': '...',
               'title': {'text': 'Bitcoin Candlestick Chart'},
               'xaxis': {'title': {'text': 'Date'}},
               'yaxis': {'title': {'text': 'Price (USD)'}}}
})